#line 1 "lex.yy.c"

#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* %endif */

/* %if-not-reentrant */
/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

/* %endif */

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	yyg->yy_c_buf_p = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[366] =
    {   0,
       87,   85,   86,   84,   85,   86,   82,   86,   83,   85,
       86,   81,   85,   86,   85,   86,   85,   86,   81,   85,
       86,   85,   86,   85,   86,   81,   85,   86,   81,   85,
       86,   81,   85,   86,   81,   85,   86,   81,   85,   86,
       73,   85,   86,   73,   85,   86,   81,   85,   86,   81,
       85,   86,   81,   85,   86,   81,   85,   86,   81,   85,
       86,   77,   85,   86,   77,   81,   85,   86,   77,   85,
       86,   77,   85,   86,   77,   85,   86,   77,   85,   86,
       77,   85,   86,   77,   85,   86,   77,   85,   86,   77,
       85,   86,   77,   85,   86,   77,   85,   86,   77,   85,

       86,   77,   85,   86,   77,   85,   86,   77,   85,   86,
       77,   85,   86,   77,   85,   86,   81,   85,   86,   85,
       86,    6,   86,    3,   86,    5,   86,    6,   86,   12,
       86,   11,   12,   86,   11,   86,   10,   12,   86,   12,
       86,   12,   86,   14,   86,   86,   84,   56,   72,   23,
       60,   67,   54,   65,   53,   66,   63,   76,   78,    1,
        2,   68,   69,   73,   70,   64,   61,   57,   55,   58,
       62,   71,   77,   79,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   33,   77,   77,   34,   77,   40,   77,
       77,   77,   77,   51,   77,   77,   77,   77,   77,   77,

       77,   77,   77,   77,   59,   74,   13,    4,   11,   14,
       15,   80,   80,   78,   76,   73,   73,   77,   52,   77,
       77,   77,   77,   77,   77,   77,   77,   35,   77,   77,
       77,   77,   77,   28,   77,   77,   77,   77,   77,   77,
       42,   77,   77,   77,   75,   74,    9,16392,   18,   77,
       77,   26,   77,   77,   77,   77,   36,   77,   38,   77,
       27,   77,   77,   77,   45,   77,   41,   77,   77,   77,
       77,   37,   77,   77,   77,   77, 8200,   21,   22,   19,
       77,   31,   77,   29,   77,   77,   48,   77,   77,   77,
       77,   77,   46,   77,   77,   77,   24,   77,   77,   77,

       77,   44,   77,   39,   77,   25,   77,   77,   77,   20,
       16,   77,   77,   77,   43,   77,   47,   77,   77,    7,
       77,   77,   32,   77,   30,   77,   17,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   50,   77,   49,   77
    } ;

static const flex_int16_t yy_accept[308] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       19,   22,   24,   26,   29,   32,   35,   38,   41,   44,
       47,   50,   53,   56,   59,   62,   65,   69,   72,   75,
       78,   81,   84,   87,   90,   93,   96,   99,  102,  105,
      108,  111,  114,  117,  120,  122,  124,  126,  128,  130,
      132,  135,  137,  140,  142,  144,  146,  147,  148,  149,
      149,  150,  150,  151,  151,  151,  151,  151,  151,  151,
      151,  152,  152,  152,  152,  153,  154,  155,  156,  157,
      158,  159,  160,  161,  162,  164,  164,  165,  165,  165,

      166,  167,  168,  169,  170,  171,  172,  173,  174,  175,
      176,  177,  178,  179,  180,  181,  182,  183,  184,  186,
      187,  189,  191,  192,  193,  194,  196,  197,  198,  199,
      200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
      210,  210,  210,  211,  211,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  213,  214,  214,  214,  215,  216,
      217,  218,  219,  221,  222,  223,  224,  225,  226,  227,
      228,  230,  231,  232,  233,  234,  236,  237,  238,  239,
      240,  241,  243,  244,  245,  246,  247,  249,  249,  249,
      249,  249,  249,  249,  249,  250,  250,  250,  251,  252,

      254,  255,  256,  257,  259,  261,  263,  264,  265,  267,
      269,  270,  271,  272,  274,  275,  276,  277,  278,  278,
      278,  279,  280,  280,  281,  281,  281,  281,  282,  284,
      286,  287,  289,  290,  291,  292,  293,  295,  296,  297,
      299,  299,  299,  299,  299,  300,  301,  302,  304,  306,
      308,  309,  310,  311,  311,  311,  312,  313,  314,  315,
      317,  319,  320,  321,  321,  322,  323,  325,  327,  328,
      329,  330,  331,  332,  333,  334,  335,  336,  337,  338,
      339,  340,  341,  342,  343,  344,  345,  346,  347,  348,
      349,  350,  351,  352,  353,  354,  355,  356,  357,  358,

      359,  360,  361,  362,  364,  366,  366
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   33,   35,   36,
       37,   37,   38,   37,   39,   40,   37,   41,   42,   43,
       37,   44,   45,   46,   47,   37,   37,   48,   37,   37,
       49,   50,   51,   52,   53,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   37,   63,   64,   65,   66,
       67,   68,   37,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,   79,   80,   81,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    1,    1,    1,    5,    5,    5,
        6,    6,    6,    7,    1,    1,    1,    1,    1,    3,
        1,    8,    8,    8,    8,    8,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    1,   10,
        1,    1,   11,   12,   12,    8,    8,    8,   12,    9,
        9,    9,    9,    9,    9,   13,    9,    9,   13,    9,
       13,    9,   13,    9,   13,    9,    9,   14,    1,    1,
       15
    } ;

static const flex_int16_t yy_base[323] =
    {   0,
        0,    0,  706,  705,   79,   80,   82,   86,  102,  108,
      626,  625,  705,  710,  702,  710,  710,  675,   86,   62,
      710,  691,   47,  673,   86,   99,  116,  126,  126,  134,
       91,   95,  672,  114,  671,  620,   47,   42,   82,   98,
       86,  105,   95,  104,   99,  100,  106,  110,  115,  118,
      109,  107,  129,  618,  615,  710,  710,  710,  675,  710,
      195,  200,  710,    0,    0,  613,  612,  690,  710,  184,
      710,    0,  710,  624,  144,  624,  627,  619,  620,  610,
      710,  673,  197,  672,  710,  710,  710,  710,  710,  710,
      189,    0,  710,  710,  710,  193,  202,  206,    0,  710,

      710,  710,  710,  710,  710,  710,  710,  605,  710,  163,
      165,  171,  160,  166,  172,  177,  167,   20,  604,  170,
      603,  179,  183,  176,  182,  602,  180,  178,  174,  200,
      195,  196,  204,  199,  203,  710,  666,  710,  710,  264,
      671,  648,  595,  594,  710,  610,  609,  618,  615,  604,
      602,  596,  599,  710,  654,  263,    0,    0,  266,  249,
        0,  228,  586,  225,  222,  221,  235,  233,  237,  218,
      585,  234,  229,  239,  238,  584,  232,  243,  241,  245,
      247,  577,  264,  256,  710,  637,  305,  575,  588,  585,
      574,  573,  556,  559,  710,  314,  615,  282,  265,  547,

      260,  267,  261,  546,  510,  507,  255,  268,  506,  499,
      284,  285,  288,  491,  291,  277,  292,  710,  332,  486,
      710,  710,  415,  710,  424,  429,  472,  298,  405,  404,
      286,  403,  296,  299,  283,  295,  401,  289,  303,  400,
      411,  418,  417,  415,  336,  300,  321,  394,  391,  390,
      305,  316,  710,  408,  407,  710,  314,  337,  326,  386,
      383,  328,  710,  401,  341,  345,  379,  361,  710,  351,
      346,  355,  340,  357,  364,  363,  353,  362,  348,  371,
      365,  367,  373,  356,  366,  376,  368,  370,  381,  384,
      369,  372,  377,  382,  392,  375,  385,  393,  389,  402,

      398,  411,  410,   56,   53,  710,  489,  504,  519,  534,
      549,  559,  567,  574,  585,  594,  607,  620,  628,  636,
      645,  653
    } ;

static const flex_int16_t yy_def[323] =
    {   0,
      306,    1,  307,  307,  307,  307,  308,  308,  308,  308,
      309,  309,  306,  306,  306,  306,  306,  306,  310,  306,
      306,  306,  311,  306,  306,  306,  312,  306,  306,  306,
      306,  306,  306,  306,  306,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  306,  314,  306,  306,  306,  306,  306,
      306,  306,  306,  315,  316,  317,  317,  306,  306,  310,
      306,  310,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  318,  306,  306,  306,  306,  306,  306,  306,
      306,  319,  306,  306,  306,  306,  306,  306,  320,  306,

      306,  306,  306,  306,  306,  306,  306,  313,  306,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  306,  321,  306,  306,  306,
      315,  316,  317,  317,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  322,  319,  306,  306,
      320,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  306,  321,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  322,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      306,  306,  306,  306,  313,  313,  313,  313,  313,  313,
      313,  313,  306,  306,  306,  306,  313,  313,  313,  313,
      313,  313,  306,  306,  313,  313,  313,  313,  306,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,    0,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306
    } ;

static const flex_int16_t yy_nxt[792] =
    {   0,
       14,   15,   16,   14,   17,   18,   19,   20,   21,   21,
       22,   23,   21,   21,   24,   25,   21,   26,   27,   28,
       29,   30,   30,   30,   31,   21,   32,   33,   34,   35,
       21,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   21,   14,
       21,   21,   37,   38,   39,   40,   41,   42,   43,   36,
       36,   44,   36,   36,   45,   46,   47,   36,   48,   49,
       50,   51,   52,   53,   36,   36,   36,   21,   54,   21,
       55,   58,   58,   61,   62,   61,   61,   61,   62,   61,
       61,  170,   71,   59,   59,   73,   83,  109,   63,  110,

       84,   86,   63,   61,   62,   61,   61,  111,   64,   61,
       62,   61,   61,   87,   64,  100,   88,   74,  101,  109,
       75,  102,  103,   76,  109,   77,   89,   90,   65,   78,
      109,   79,   80,  109,   65,   72,   91,   91,   91,   91,
       93,  105,  106,  115,   96,   94,   97,   97,   97,   97,
      112,  113,   96,   95,   97,   97,   97,   97,  116,  109,
      119,  120,  121,  109,  114,  123,  124,  127,  117,  122,
      118,  125,  109,  134,  126,  109,  109,  109,  133,  131,
       98,  109,  109,  109,  109,  128,  109,  109,  129,  135,
       71,  130,  109,  132,  162,  109,  140,  140,  140,  140,

       99,  140,  140,  140,  140,  147,  109,  148,  155,   91,
       91,   91,   91,  159,  159,  159,  159,  156,  156,  156,
       96,  163,   97,   97,   97,   97,  160,  160,  164,  165,
      167,  166,  168,   72,  172,  178,  169,  109,  171,  173,
      109,  174,  109,  109,  109,  175,  177,  109,  109,  109,
      176,  109,  179,  109,  109,  109,  109,  109,  180,  109,
      109,  182,  183,  181,  184,  140,  140,  140,  140,  160,
      160,  157,  109,  109,  154,  198,  109,  109,  199,  200,
      109,  109,  206,  196,  196,  196,  159,  159,  159,  159,
      201,  202,  203,  204,  205,  109,  209,  207,  109,  109,

      208,  210,  109,  211,  215,  109,  109,  213,  214,  109,
      109,  109,  109,  212,  109,  109,  109,  216,  109,  217,
      109,  218,  109,  228,  109,  154,  233,  229,  231,  232,
      230,  234,  109,  109,  227,  227,  227,  109,  109,  235,
      236,  109,  109,  238,  109,  109,  237,  239,  218,  240,
      245,  246,  247,  249,  109,  250,  248,  265,  251,  109,
      109,  109,  109,  109,  252,  109,  109,  257,  109,  109,
      258,  259,  109,  109,  219,  109,  109,  109,  260,  262,
      109,  261,  109,  267,  266,  268,  270,  271,  272,  273,
      274,  109,  275,  109,  276,  277,  278,  279,  109,  280,

      281,  219,  282,  109,  285,  109,  284,  283,  286,  287,
      288,  290,  289,  109,  109,  291,  298,  109,  109,  292,
      295,  293,  109,  109,  294,  109,  297,  296,  109,  299,
      109,  300,  109,  109,  109,  301,  302,  303,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  304,  109,  109,  109,  305,  109,  269,  109,  109,
      109,  109,  109,  109,  264,  263,  109,  109,  109,  109,
      109,  109,  256,  255,  254,  109,  253,  109,  109,  109,
      109,  109,  109,  154,  244,  243,  242,  109,  109,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   82,
      241,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   92,   92,   92,   92,  109,   92,
       92,   92,  108,  108,  108,  108,  109,  108,  108,  108,
      108,  137,  137,  109,  109,  137,  137,  109,  137,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  142,  142,

      142,  142,  142,  142,  142,  142,  142,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,   82,  109,  109,   82,  154,  226,  225,   82,
      224,   82,   82,  158,  158,  158,  158,  223,  158,  158,
      158,  161,  161,  161,  222,  221,  220,  161,  186,  185,
      186,  186,  186,  186,  109,  186,  186,  186,  197,  197,
      197,  109,  109,  109,  197,  154,  195,  194,  193,  192,
      191,  190,  189,  188,  306,  144,  187,  187,  185,  109,
      109,  109,  109,  154,  154,  153,  152,  151,  150,  149,
      146,   68,  145,  144,  139,  138,  136,  109,  107,  104,

       85,   81,   69,   68,  306,   67,   67,   57,   57,   13,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306

    } ;

static const flex_int16_t yy_chk[792] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    7,    7,    7,    8,    8,    8,
        8,  118,   19,    5,    6,   20,   23,  118,    7,   37,

       23,   25,    8,    9,    9,    9,    9,   38,    9,   10,
       10,   10,   10,   25,   10,   31,   26,   20,   31,   38,
       20,   32,   32,   20,   37,   20,   26,   26,    9,   20,
      305,   20,   20,  304,   10,   19,   27,   27,   27,   27,
       28,   34,   34,   41,   29,   28,   29,   29,   29,   29,
       39,   40,   30,   28,   30,   30,   30,   30,   42,   39,
       43,   43,   44,   41,   40,   45,   46,   48,   42,   44,
       42,   46,   43,   52,   47,   40,   45,   46,   51,   50,
       29,   44,   42,   47,   52,   49,   51,   48,   49,   53,
       70,   49,   49,   50,  110,   50,   61,   61,   61,   61,

       29,   62,   62,   62,   62,   75,   53,   75,   83,   91,
       91,   91,   91,   96,   96,   96,   96,   83,   83,   83,
       97,  111,   97,   97,   97,   97,   98,   98,  112,  113,
      115,  114,  116,   70,  122,  129,  117,  113,  120,  123,
      110,  124,  111,  114,  117,  125,  128,  120,  112,  115,
      127,  129,  130,  124,  116,  128,  122,  127,  131,  125,
      123,  133,  134,  132,  135,  140,  140,  140,  140,  160,
      160,   83,  131,  132,  156,  162,  134,  130,  164,  165,
      135,  133,  170,  156,  156,  156,  159,  159,  159,  159,
      166,  166,  167,  168,  169,  170,  174,  172,  166,  165,

      173,  175,  164,  177,  181,  162,  173,  179,  180,  177,
      168,  172,  167,  178,  169,  175,  174,  183,  179,  184,
      178,  187,  180,  198,  181,  196,  207,  199,  202,  203,
      201,  208,  207,  184,  196,  196,  196,  201,  203,  211,
      212,  183,  199,  215,  202,  208,  213,  216,  219,  217,
      228,  231,  233,  235,  216,  236,  234,  257,  238,  198,
      235,  211,  212,  231,  239,  213,  238,  245,  215,  217,
      245,  246,  236,  233,  187,  228,  234,  246,  247,  252,
      239,  251,  251,  259,  258,  262,  265,  266,  270,  271,
      272,  257,  273,  252,  274,  275,  276,  277,  247,  278,

      279,  219,  280,  259,  283,  262,  282,  281,  284,  285,
      286,  288,  287,  245,  258,  289,  296,  273,  265,  290,
      293,  291,  266,  271,  292,  279,  295,  294,  270,  297,
      277,  298,  272,  284,  274,  299,  300,  301,  268,  278,
      276,  275,  281,  285,  282,  287,  291,  288,  280,  292,
      283,  302,  296,  286,  293,  303,  267,  264,  289,  294,
      261,  290,  297,  260,  255,  254,  299,  250,  249,  295,
      298,  248,  244,  243,  242,  301,  241,  240,  237,  300,
      232,  230,  229,  227,  226,  225,  223,  303,  302,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  311,
      220,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  312,  312,  312,  312,  214,  312,
      312,  312,  313,  313,  313,  313,  210,  313,  313,  313,
      313,  314,  314,  209,  206,  314,  314,  205,  314,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  318,  204,  200,  318,  197,  194,  193,  318,
      192,  318,  318,  319,  319,  319,  319,  191,  319,  319,
      319,  320,  320,  320,  190,  189,  188,  320,  321,  186,
      321,  321,  321,  321,  182,  321,  321,  321,  322,  322,
      322,  176,  171,  163,  322,  155,  153,  152,  151,  150,
      149,  148,  147,  146,  144,  143,  142,  141,  137,  126,
      121,  119,  108,   84,   82,   80,   79,   78,   77,   76,
       74,   68,   67,   66,   59,   55,   54,   36,   35,   33,

       24,   22,   18,   15,   13,   12,   11,    4,    3,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306

    } ;

static const flex_int16_t yy_rule_linenum[86] =
    {   0,
      100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
      110,  111,  115,  116,  117,  118,  119,  120,  121,  122,
      123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
      133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
      143,  144,  145,  146,  147,  148,  149,  150,  151,  155,
      159,  160,  162,  163,  164,  165,  166,  167,  168,  169,
      170,  171,  172,  174,  175,  176,  177,  178,  179,  180,
      181,  183,  184,  197,  201,  205,  206,  207,  214,  225,
      229,  230,  231,  232,  233
    } ;

#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yyg->yy_full_match; /* restore poss. backed-over text */ \
yyg->yy_lp = yyg->yy_full_lp; /* restore orig. accepting pos. */ \
yyg->yy_state_ptr = yyg->yy_full_state; /* restore orig. state */ \
yy_current_state = *yyg->yy_state_ptr; /* restore curr. state */ \
++yyg->yy_lp; \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "scan.l"
#line 4 "scan.l"
  #include "src/utils/utils.h"
  #include "src/axo.h"
  #include "axo_gram.tab.h"
  int yylex(YYSTYPE* yylval_param, YYLTYPE* yyloc_param, yyscan_t scanner);
    YYLTYPE yylloc = (YYLTYPE){
    .first_line = 1,
    .first_column = 1,
    .last_line = 1,
    .last_column = 1
  };
  
  extern int prog_return;
  extern axo_state* state;
  void axo_pop_source(axo_state* st);
  void axo_add_decl(axo_state* st, axo_decl decl);
  int yywrap(yyscan_t yyscanner);
  // void axo_yyerror(YYLTYPE* loc, const char * fmt, ...);
  //Reentrant scanner bs
  // typedef struct yyguts_t *yyscan_t; // Ensure you have this typedef

#define YY_INPUT(buf, result, max_size) \
{ \
  axo_source* src = axo_get_source(state); \
  char* str; \
  switch(src->kind){ \
    case axo_string_source_kind: \
      str = src->str; \
      int LEN = strlen(str + axo_src_index(state)); \
      result = max_size > LEN ? LEN : max_size; \
      if (result>0){ \
        memcpy(buf, str + axo_src_index(state), result); \
      } \
      axo_src_index(state) += result; \
      break; \
    case axo_file_source_kind: \
      if ((result = fread(buf, 1, max_size, yyin)) < 0) \
        YY_FATAL_ERROR("input in flex scanner failed"); \
      break; \
  } \
}

  void bin_to_hex_lit(char *bin, int len) {
    char hex_char[17] = "0123456789ABCDEF";
    int i = 0;
    int j = 0;
    while (i<len){
      int hex = 0;
      int mult = 8;
      while (i<len){
        if (bin[i++] == '1') hex+=mult;
        if (mult == 1) break;
        mult /= 2;
      }
      bin[j++] = hex_char[hex];
    }
    bin[j] = '\0';
  }

  #define axo_adv_loc(ST) ({ \
    yylloc->first_line=yylloc->last_line=axo_line(ST); \
    yylloc->first_column=axo_col(ST); \
    yylloc->last_column=axo_col(ST)=axo_col(ST)+yyleng; \
  })
  #define axo_ret_def(ST) ({ \
    yylloc->first_line=yylloc->last_line=axo_line(ST); \
    yylloc->first_column=axo_col(ST); \
    yylloc->last_column=axo_col(ST)+=yyleng; \
    yylval->str=alloc_str(yytext); \
  })
  #define axo_ret_null(ST) ({ \
    yylloc->first_line=yylloc->last_line=axo_line(ST); \
    yylloc->first_column=axo_col(ST); \
    yylloc->last_column=axo_col(ST)+=yyleng; \
    yylval->str=""; \
  })

  #define ret_null axo_ret_null(state)
  #define ret_def axo_ret_def(state)
  #define adv_loc axo_adv_loc(state)
  
  #define YY_NO_INPUT
  #define YY_USER_ACTION axo_pos(state)+=yyleng;
  
#line 934 "lex.yy.c"

#line 936 "lex.yy.c"

#define INITIAL 0
#define SINGLE_LINE_COMMENT 1
#define MULTI_LINE_COMMENT 2
#define INCLUDE_MORE_ST 3
#define INCLUDE_ST 4
#define COMPTIME_LUA_ST 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    yy_state_type *yy_state_buf;
    yy_state_type *yy_state_ptr;
    char *yy_full_match;
    int yy_lp;

    /* These are only needed for trailing context rules,
     * but there's no conditional variable for that yet. */
    int yy_looking_for_trail_begin;
    int yy_full_lp;
    int *yy_full_state;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

/* %if-c-only */

static int yy_init_globals ( yyscan_t yyscanner );

/* %endif */

/* %if-reentrant */

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* %endif */

/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! yyg->yy_state_buf )
            yyg->yy_state_buf = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  , yyscanner);
            if ( ! yyg->yy_state_buf )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
/* %% [7.0] user's declarations go here */
#line 97 "scan.l"

#line 99 "scan.l"
  
#line 1289 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = yyg->yy_start;

		yyg->yy_state_ptr = yyg->yy_state_buf;
		*yyg->yy_state_ptr++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*yyg->yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 710 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_current_state = *--yyg->yy_state_ptr;
		yyg->yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yyg->yy_lp && yyg->yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yyg->yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yyg->yy_looking_for_trail_begin )
					{
					if ( yy_act == yyg->yy_looking_for_trail_begin )
						{
						yyg->yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yyg->yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yyg->yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yyg->yy_full_match = yy_cp;
					yyg->yy_full_state = yyg->yy_state_ptr;
					yyg->yy_full_lp = yyg->yy_lp;
					break;
					}
				++yyg->yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yyg->yy_state_ptr;
			yyg->yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 86 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 86 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 87 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
case 1:
YY_RULE_SETUP
#line 100 "scan.l"
{BEGIN(MULTI_LINE_COMMENT);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 101 "scan.l"
{BEGIN(SINGLE_LINE_COMMENT);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 102 "scan.l"
{axo_line(state)++; axo_col(state)=1; BEGIN(INITIAL);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "scan.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 104 "scan.l"
{axo_line(state)++; axo_col(state)=1;};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 105 "scan.l"
axo_col(state)++;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "scan.l"
{adv_loc; BEGIN(INCLUDE_ST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 107 "scan.l"
{ret_def; BEGIN(INCLUDE_MORE_ST); return C_INCLUDE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 108 "scan.l"
{ret_def; BEGIN(INITIAL); return C_INCLUDE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "scan.l"
{adv_loc; BEGIN(INCLUDE_ST);}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 110 "scan.l"
{adv_loc;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "scan.l"
{
    adv_loc;
    axo_yyerror(yylloc, "Unexpected '%c' in a #include macro.", yytext[0]);
  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "scan.l"
{ BEGIN(COMPTIME_LUA_ST); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 116 "scan.l"
{ret_def; return COMPTIME_LUA_BLOCK;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "scan.l"
{BEGIN(INITIAL); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "scan.l"
{ret_null; return SOURCE_TAG; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "scan.l"
{ret_null; return PROVIDED_TAG; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "scan.l"
{ret_null; return TAG_TYP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "scan.l"
{ret_null; return LINE_TAG; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "scan.l"
{ret_null; return COLUMN_TAG; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "scan.l"
{ret_null; return FILE_TAG; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "scan.l"
{ret_null; return FLAG_TAG; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "scan.l"
{ret_null; return C_TAG; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "scan.l"
{ret_null; return WHILE_KWRD; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "scan.l"
{ret_null; return SWITCH_KWRD; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "scan.l"
{ret_null; return CASE_KWRD; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "scan.l"
{ret_null; return ENUM_KWRD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "scan.l"
{ret_null; return RET_KWRD; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "scan.l"
{ret_null; return CONST_KWRD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "scan.l"
{ret_null; return VOLATILE_KWRD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "scan.l"
{ret_null; return BREAK_KWRD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "scan.l"
{ret_null; return CONTINUE_KWRD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 135 "scan.l"
{ret_null; return FN_KWRD; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "scan.l"
{ret_null; return IF_KWRD; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 137 "scan.l"
{ret_null; return FOR_KWRD; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 138 "scan.l"
{ret_null; return EACH_KWRD; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 139 "scan.l"
{ret_null; return TILL_KWRD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 140 "scan.l"
{ret_null; return ELSE_KWRD; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 141 "scan.l"
{ret_null; return STRUCT_KWRD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 142 "scan.l"
{ret_null; return IN_KWRD; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 143 "scan.l"
{ret_null; return NULL_KWRD; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 144 "scan.l"
{ret_null; return USE_KWRD; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 145 "scan.l"
{ret_null; return INCLUDE_KWRD; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 146 "scan.l"
{ret_null; return MODULE_KWRD; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 147 "scan.l"
{ret_null; return NONE_KWRD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 148 "scan.l"
{ret_null; return SZ_OF_KWRD;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 149 "scan.l"
{ret_null; return TYPE_SZ_KWRD;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 150 "scan.l"
{ret_null; return DEFER_KWRD;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 151 "scan.l"
{
  ret_null;
  return AXO_EXPR_AS_PARSE_RESULT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 155 "scan.l"
{
  return 0;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 159 "scan.l"
{ret_null; return BIT_OR_OP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 160 "scan.l"
{ret_null; return BIT_AND_OP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 162 "scan.l"
{ret_null; return DECR_OP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 163 "scan.l"
{ret_null; return INCR_OP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 164 "scan.l"
{ret_null; return EQ_OP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 165 "scan.l"
{ret_null; return INEQ_OP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 166 "scan.l"
{ret_null; return EQ_GRTR_OP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "scan.l"
{ret_null; return EQ_SMLR_OP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 168 "scan.l"
{ret_null; return LOGICAL_OR_OP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "scan.l"
{ret_null; return LOGICAL_AND_OP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 170 "scan.l"
{ret_null; return LEFT_SHIFT_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 171 "scan.l"
{ret_null; return RIGHT_SHIFT_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 172 "scan.l"
{ret_null; return ARROW_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 174 "scan.l"
{ret_null; return WALRUS_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 175 "scan.l"
{ret_null; return ASSIGN_ADD; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 176 "scan.l"
{ret_null; return ASSIGN_SUB; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 177 "scan.l"
{ret_null; return ASSIGN_MUL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 178 "scan.l"
{ret_null; return ASSIGN_DIV; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 179 "scan.l"
{ret_null; return ASSIGN_MOD; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 180 "scan.l"
{ret_null; return MODULE_ACCESS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 181 "scan.l"
{ret_null; return ASSIGN_AND_CALL_ERROR; }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 183 "scan.l"
{ret_def; return(STRING_LITERAL); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 184 "scan.l"
{
  ret_def;
  //Return the literal directly if it's not binary
  if (yyleng<=3 || yytext[1] != 'b'){
    return(INTEGER_LITERAL);
  }
  bin_to_hex_lit(&(yytext[2]), yyleng-2);
  yytext[1] = 'x';
  char* prev = yylval->str;
  yylval->str=alloc_str(yytext);
  free(prev);
  return(INTEGER_LITERAL);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 197 "scan.l"
{
  ret_def;
  return COMPTIME_VAR;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 201 "scan.l"
{
  ret_def;
  return COMPTIME_CALL;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 205 "scan.l"
{ret_def; return FLOAT_LITERAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 206 "scan.l"
{ret_def; return IDEN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 207 "scan.l"
{
    yylloc->first_line=yylloc->last_line=axo_line(state);
    yylloc->first_column=axo_col(state);
    yylloc->last_column=axo_col(state)+=yyleng;
    yylval->str=alloc_str(&(yytext[1]));
    return DOT_FIELD;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 214 "scan.l"
{
  ret_def;
  yylval->str[yyleng-1] = '\0';
  //Super dirty! Changes needed to structure literals
  if (strcmp(yylval->str, "else") == 0){
    unput('{');
    return ELSE_KWRD;
  }else{
    return STRUCT_LITERAL_START;
  }
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 225 "scan.l"
{
  ret_def;
  return BYTE_LITERAL;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 229 "scan.l"
{ret_def; return yytext[0]; }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 230 "scan.l"
{axo_line(state)++; axo_col(state)=1;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 231 "scan.l"
;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 232 "scan.l"
{axo_col(state)+=yyleng;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 233 "scan.l"
{ 
    ret_null;
      axo_yyerror(NULL, "Unexpected '%c'(%d) at %s:%d:%d in input.", yytext[0], yytext[0], axo_src_name(state), yylloc->first_line, yylloc->first_column);
  }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 238 "scan.l"
ECHO;
	YY_BREAK
#line 1876 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(SINGLE_LINE_COMMENT):
			case YY_STATE_EOF(MULTI_LINE_COMMENT):
			case YY_STATE_EOF(INCLUDE_MORE_ST):
			case YY_STATE_EOF(INCLUDE_ST):
			case YY_STATE_EOF(COMPTIME_LUA_ST):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = yyg->yy_start;

	yyg->yy_state_ptr = yyg->yy_state_buf;
	*yyg->yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*yyg->yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
/* %% [17.0] code to find the next state, and perhaps do backing up, goes here */

	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 306);
	if ( ! yy_is_jam )
		*yyg->yy_state_ptr++ = yy_current_state;

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
/* %if-c-only */
void yypop_buffer_state (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (yyscan_t yyscanner)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/* %endif */

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/* %if-reentrant */

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* Accessor methods for yylval and yylloc */

/* %if-bison-bridge */
/* %endif */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

    yyg->yy_state_buf = 0;
    yyg->yy_state_ptr = 0;
    yyg->yy_full_match = 0;
    yyg->yy_lp = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    yyfree ( yyg->yy_state_buf , yyscanner);
    yyg->yy_state_buf  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

/* %if-reentrant */
    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 238 "scan.l"

int yywrap(yyscan_t scanner) {
  if (state->in_core){
    state->in_core = false;
    axo_add_decl(state, (axo_decl){.kind=axo_assign_decl_kind, .val=NULL});
    state->modules_decl = state->decls_len-1;
  }
  if (state->sources_len>1){
    axo_pop_source(state);
    return 0;
  }
  return 1;
}

//FIX: else{ ?

